{% set name = "qcodes" %}
{% set version = "0.1.11" %}
{% set sha256 = "9cac506829f866aac98e772c613686607dce95b5aece13280793dffea36f32f1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.zip
  url: https://github.com/QCoDeS/Qcodes/archive/v{{ version }}.zip
  sha256: {{ sha256 }}

build:
  number: 1000
  skip: true  # [py<35]
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - numpy >=1.10
    - pyvisa >=1.8
    - h5py >=2.6
    - websockets >=3.2
    - jsonschema
    - pyzmq

test:
  imports:
    - qcodes

about:
  home: http://qcodes.github.io/Qcodes/
  license: MIT
  # license_file: LICENSE.md
  summary: 'Modular data acquisition and analysis framework'
  description: |
    QCoDeS is a Python-based data acquisition framework developed 
    by the Copenhagen / Delft / Sydney / Microsoft quantum computing 
    consortium. While it has been developed to serve the needs of 
    nanoelectronic device experiments, it is not inherently limited 
    to such experiments, and can be used anywhere a system with many 
    degrees of freedom is controllable by computer.
  doc_url: http://qcodes.github.io/Qcodes/
  dev_url: https://github.com/QCoDeS/Qcodes

extra:
  recipe-maintainers:
    - basnijholt
    - AdriaanRol
