{% set name = "qcodes" %}
{% set version = "0.49.0" %}

package:
  name: qcodes
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 12bdc7a58204202a87f1a623f1455df959f9d690f9552ad20f6cb0277c9c6a73

build:
  number: 1
  skip: true  # [py<=39]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - versioningit
    - setuptools
  run:
    - python
    - numpy >=1.22.4
    - pyvisa >=1.11.0, <1.15
    - h5py >=3.6.0
    - websockets >=11.0
    - jsonschema >=4.9.0
    - ruamel.yaml >=0.16.0, !=0.16.6
    - wrapt >=1.14.0  # [py<312]
    - wrapt >=1.16.0  # [py>=312]
    - pandas >=1.4.0
    - xarray >=2022.06.0
    - cf_xarray >=0.8.4
    - tabulate >=0.9.0
    - tqdm >=4.59.0
    - matplotlib-base >=3.5.0
    - typing_extensions >=4.6.0
    - packaging >=20.0
    - ipywidgets >=8.0.0, <9.0.0
    - broadbean >=0.11.0
    - uncertainties >=3.1.4
    - h5netcdf >=0.14.1
    - opentelemetry-api >=1.15.0
    - dask >=2022.1.0
    - pillow >=9.0.0

test:
  imports:
    - qcodes

about:
  home: http://microsoft.github.io/Qcodes
  license: MIT
  license_file: LICENSE
  summary: Modular data acquisition and analysis framework
  description: |
    QCoDeS is a Python-based data acquisition framework developed
    by the Copenhagen / Delft / Sydney / Microsoft quantum computing
    consortium. While it has been developed to serve the needs of
    nanoelectronic device experiments, it is not inherently limited
    to such experiments, and can be used anywhere a system with many
    degrees of freedom is controllable by computer.
  doc_url: http://microsoft.github.io/Qcodes
  dev_url: https://github.com/microsoft/Qcodes

extra:
  recipe-maintainers:
    - basnijholt
    - jenshnielsen
    - astafan8
    - einsmein
    - picarro-yren
    - samantha-ho
    - trevormorgan
