{% set name = "qcodes" %}
{% set version = "0.1.3" %}
{% set sha256 = "2ad965790f91be61b464e10d9fd35cd0ff153a49eab088c7b50c6fa9ee638925" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.zip
  url: https://github.com/QCoDeS/Qcodes/archive/v{{ version }}.zip
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [not py35]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - numpy >=1.10*,
    - pyvisa >=1.8*,
    - ipython >=4.1*,
    - jupyter >=1.0*
    - h5py >=2.6*
    - matplotlib >=1.5*
    - pyqtgraph >=0.10*
    - coverage >=4.0*

test:
  source_files:
    - qcodes/test.py
  commands:
    - python qcodes/test.py
  imports:
    - qcodes

about:
  home: http://qcodes.github.io/Qcodes/
  license: MIT
  license_file: LICENSE.rst
  summary: 'Modular data acquisition and analysis framework'
  description: |
    QCoDeS is a Python-based data acquisition framework developed 
    by the Copenhagen / Delft / Sydney / Microsoft quantum computing 
    consortium. While it has been developed to serve the needs of 
    nanoelectronic device experiments, it is not inherently limited 
    to such experiments, and can be used anywhere a system with many 
    degrees of freedom is controllable by computer.
  doc_url: http://qcodes.github.io/Qcodes/
  dev_url: https://github.com/QCoDeS/Qcodes

extra:
  recipe-maintainers:
    - basnijholt
    - AdriaanRol
