{% set version = "0.16.0" %}

package:
  name: qcodes
  version: {{ version }}

source:
  url: https://github.com/QCoDeS/Qcodes/archive/v{{ version }}.tar.gz
  sha256: cd432dc30678c98d272821225603cfd741bf60e75002243e323b7778edfa4115

build:
  number: 0
  skip: true  # [py27]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
  run:
    - python
    - numpy >=1.10
    - pyvisa >=1.9.1
    - h5py >=2.6
    - websockets >=7.0
    - jsonschema
    - ruamel.yaml
    - pyzmq
    - wrapt
    - pandas
    - tabulate
    - tqdm
    - opencensus-ext-azure
    - matplotlib >=2.2.3
    - dataclasses  # [py<37]
    - requirements-parser
    - importlib_metadata  # [py<38]
    - typing_extensions
    - packaging >=20.0

test:
  imports:
    - qcodes

about:
  home: http://qcodes.github.io/Qcodes/
  license: MIT
  license_file: LICENSE
  summary: Modular data acquisition and analysis framework
  description: |
    QCoDeS is a Python-based data acquisition framework developed 
    by the Copenhagen / Delft / Sydney / Microsoft quantum computing 
    consortium. While it has been developed to serve the needs of 
    nanoelectronic device experiments, it is not inherently limited 
    to such experiments, and can be used anywhere a system with many 
    degrees of freedom is controllable by computer.
  doc_url: http://qcodes.github.io/Qcodes/
  dev_url: https://github.com/QCoDeS/Qcodes

extra:
  recipe-maintainers:
    - basnijholt
