{% set name = "qcodes" %}
{% set version = "0.33.0" %}

package:
  name: qcodes
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bf2dc232fa9cc0a9d57d719624b1faa391faa5f4f3bf26a98e108001b5c24787

build:
  number: 0
  skip: true  # [py<=36]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy >=1.17.0
    - pyvisa >=1.11.0, <1.12
    - h5py >=2.10.0
    - websockets >=7.0
    - jsonschema >=3.0.0
    - ruamel.yaml >=0.16.0, !=0.16.6
    - wrapt >=1.10.4
    - pandas >=1.0.0
    - xarray >=0.18.0
    - tabulate >=0.8.0
    - tqdm >=4.32.2
    - opencensus >=0.7.10, <0.9.0
    - opencensus-ext-azure >=1.0.4, <2.0.0
    - matplotlib-base >=3.3.0
    - importlib-metadata >=3.6.0,<5.0.0  # [py<38]
    - typing_extensions >=3.10.0
    - packaging >=20.0
    - ipywidgets >=7.5.0
    - broadbean >=0.9.1
    - uncertainties >=3.1.4
    - h5netcdf >=0.8.0
    - setuptools >=48.0.0

test:
  imports:
    - qcodes

about:
  home: http://qcodes.github.io/Qcodes
  license: MIT
  license_file: LICENSE
  summary: Modular data acquisition and analysis framework
  description: |
    QCoDeS is a Python-based data acquisition framework developed 
    by the Copenhagen / Delft / Sydney / Microsoft quantum computing 
    consortium. While it has been developed to serve the needs of 
    nanoelectronic device experiments, it is not inherently limited 
    to such experiments, and can be used anywhere a system with many 
    degrees of freedom is controllable by computer.
  doc_url: http://qcodes.github.io/Qcodes
  dev_url: https://github.com/QCoDeS/Qcodes

extra:
  recipe-maintainers:
    - basnijholt
    - jenshnielsen
    - astafan8
    - trevormorgan
    - sohailc
    - samantha-ho
    - Dominik-Vogel
