# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/73cd2eed94c576213c5f25ab57adf6d8c83e792a/schema.json
schema_version: 1

context:
  name: qcodes
  version: 0.51.0

package:
  name: qcodes
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: bde9a524adfe0640e6f84ab0e007b4d0c3fca8e7bb8c276db22562dc9467855e

build:
  number: 1
  skip: match(python, "<=3.9")
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - if: build_platform != target_platform
      then: python
    - if: build_platform != target_platform
      then: cross-python_${{ target_platform }}
  host:
    - python
    - pip
    - versioningit
    - setuptools
  run:
    - python
    - numpy >=1.22.4
    - pyvisa >=1.11.0, <1.15
    - h5py >=3.6.0
    - websockets >=11.0
    - jsonschema >=4.9.0
    - ruamel.yaml >=0.16.0, !=0.16.6
    - if: match(python, "<3.12")
      then: wrapt >=1.14.0
    - if: match(python, ">=3.12")
      then: wrapt >=1.16.0
    - pandas >=1.4.0
    - xarray >=2022.06.0
    - cf_xarray >=0.8.4
    - tabulate >=0.9.0
    - tqdm >=4.59.0
    - matplotlib-base >=3.5.0
    - typing_extensions >=4.6.0
    - packaging >=20.0
    - ipywidgets >=8.0.0, <9.0.0
    - broadbean >=0.11.0
    - uncertainties >=3.1.4
    - h5netcdf >=0.14.1
    - opentelemetry-api >=1.15.0
    - dask >=2022.1.0
    - pillow >=9.0.0

tests:
  - python:
      imports:
        - qcodes

about:
  license: MIT
  license_file: LICENSE
  summary: Modular data acquisition and analysis framework
  description: |
    QCoDeS is a Python-based data acquisition framework developed
    by the Copenhagen / Delft / Sydney / Microsoft quantum computing
    consortium. While it has been developed to serve the needs of
    nanoelectronic device experiments, it is not inherently limited
    to such experiments, and can be used anywhere a system with many
    degrees of freedom is controllable by computer.
  homepage: http://microsoft.github.io/Qcodes
  repository: https://github.com/microsoft/Qcodes
  documentation: http://microsoft.github.io/Qcodes

extra:
  recipe-maintainers:
    - basnijholt
    - jenshnielsen
    - astafan8
    - einsmein
    - picarro-yren
    - samantha-ho
    - trevormorgan
