appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: nc+SL1l+JC+N5qB6t98SL9TbbBIAbyI52/4J04FLHAVLOmwhGYgatHr9airE8gDzK2c9oJBuly0+DhF+Zfi44YoTrtxreMcCok7o1JfH0YEzBPaO2CLic2EuL/DFL7NpQndYfkiWHDubZZTrmMe8wtrslgaXQAMnMQGQ742HTjufe6pVgHKyCnpmEm0KFrYK8ESf81DBNZaxFiTlPlAqUqjM/BMFUbjMRXehHTFvY7HI6R0ZJCtiRFF3HKehCQG6HYbWZPWwRIaKUnWjLiSJ4+Bq2eAAQjdwu5TVASp0Tc5HZZd0CvPFl19Bif+7yNj/+XJB1DA3RyIY+1pS4/qUtWUXyntjF9NK41TztPZ52g76WCXknpTDQW5STJdRBzxikh2wQFBl7keUF3+duFNpwn1jyXpTiBxVK93RUkzacfqHCn0R17+39hp8UT+qGUQ8bg7sfeaxf5stlRwzxJpGlyDX9FjRXLcSejWDrkhP1gBYs7v/DZOoVZNkLiU32E2FwyAWrClZMZfiNP5pTYaSCguMthbUe5bGShJwT60/5PNZNylm2gmFsZLQlerfR5SpwDiVHiEQ2s5ALZbi2j06OkfIz2Ru5xFNdA5GbbdD+msapzMFHatbe7o3lUzxJ8DhTvVxbMzO6C+Ic3GQeSdcp3PlNz4m9GJKAD0yIPwWmvo=}
